### ISSUE TITLE
Comments are removed during transform.

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-codemods/ember-qunit-codemod#198]
Gonna submit a failing PR momentarily

**Comment by rwjblue** [comment]
In general, comments in the AST are "weird". They are effectively tacked on to the subsequent expression (e.g. not their own stand alone "thing" in the AST). In order to preserve comments you have to ensure that whenever you create a replacement AST node that you inherit the comments from the thing you are replacing.

There are a number of tests that _do_ confirm that comments are not lost (e.g. [module-for-acceptance.input.js](https://github.com/ember-codemods/ember-qunit-codemod/blob/master/transforms/convert-module-for-to-setup-test/transforms/convert-module-for-to-setup-test/__testfixtures__/module-for-acceptance.input.js) and [module-for-acceptance.output.js](https://github.com/ember-codemods/ember-qunit-codemod/blob/master/transforms/convert-module-for-to-setup-test/transforms/convert-module-for-to-setup-test/__testfixtures__/module-for-acceptance.output.js)), but its completely possible that there are other scenarios that are loosing the comments.

In order to fix, you'll need to know specifically which scenarios are loosing comments.

**Comment by NullVoxPopuli** [comment]
yup, here is the scenario: https://github.com/ember-codemods/ember-qunit-codemod/pull/199
